name: pydata-global-2022-ml-repro
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - numpy>=1.22.3
  - python>=3.10
  - jupyter>=1.0.0
  - scikit-learn>=1.1.3
  - matplotlib>=3.5.3
  - seaborn>=0.12.1
  - pandas>=1.5.1
  - pandera>=0.13.4
  - pip
  - pydantic>=1.10.2
  - pytorch>=1.13.0
  - shap>=0.41.0
  - pip:
      - surgeon-pytorch>=0.0.4
